services:
  - type: web
    name: coretech-chaves-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FIREBASE_PROJECT_ID
        value: coretech-chaves
      - key: FIREBASE_CLIENT_EMAIL
        value: firebase-adminsdk-fbsvc@coretech-chaves.iam.gserviceaccount.com