/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/identificacao`; params?: Router.UnknownInputParams; } | { pathname: `/../src/services/api`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/historico` | `/historico`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/quadro` | `/quadro`; params?: Router.UnknownInputParams; } | { pathname: `/devolucao/[codigo]`, params: Router.UnknownInputParams & { codigo: string | number; } } | { pathname: `/historico/[codigo]`, params: Router.UnknownInputParams & { codigo: string | number; } } | { pathname: `/retirada/[codigo]`, params: Router.UnknownInputParams & { codigo: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/identificacao`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/services/api`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/historico` | `/historico`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/quadro` | `/quadro`; params?: Router.UnknownOutputParams; } | { pathname: `/devolucao/[codigo]`, params: Router.UnknownOutputParams & { codigo: string; } } | { pathname: `/historico/[codigo]`, params: Router.UnknownOutputParams & { codigo: string; } } | { pathname: `/retirada/[codigo]`, params: Router.UnknownOutputParams & { codigo: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/identificacao${`?${string}` | `#${string}` | ''}` | `/../src/services/api${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/historico${`?${string}` | `#${string}` | ''}` | `/historico${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/quadro${`?${string}` | `#${string}` | ''}` | `/quadro${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/identificacao`; params?: Router.UnknownInputParams; } | { pathname: `/../src/services/api`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/historico` | `/historico`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/quadro` | `/quadro`; params?: Router.UnknownInputParams; } | `/devolucao/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/historico/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/retirada/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/devolucao/[codigo]`, params: Router.UnknownInputParams & { codigo: string | number; } } | { pathname: `/historico/[codigo]`, params: Router.UnknownInputParams & { codigo: string | number; } } | { pathname: `/retirada/[codigo]`, params: Router.UnknownInputParams & { codigo: string | number; } };
    }
  }
}
